"""Edited Role Model

Revision ID: 15c656a1dbb4
Revises: 743086797a5c
Create Date: 2024-09-13 00:49:39.163997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c656a1dbb4'
down_revision = '743086797a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
